month = int(input("enter month: "))
year = int(input("enter year: "))
date = int(input("enter date"))
dateTime_obj = datetime.date(year,month,date)
print("dateTime object at specific date",dateTime_obj)
date_time = datetime.datetime.fromtimestamp(8125723132)
print("Datetime from timestamp:", date_time)
current=datetime.datetime.now()
print("time at present=:",current)
print("current year=",current.year)
print("current month=",current.month)
print("current day=",current.day)
age=datetime.date(2023,6,20)-datetime.date(2003,4,9)
print("age=",age)
print("age in days=",age.days)
print("seconds in age=",age.seconds)