import numpy as np
arr=np.array([[1,-2,4],[-5,np.nan,0],[-10,3,np.nan]])
print(arr)
np.save('file.npy',arr)
np.load('file.npy')
mean=np.mean(arr>0)
print("mean of array:",mean)
ab=np.abs(arr)
print("Absolute values:",ab)
a=np.where(np.isnan(ab),mean,ab)
print("array after replacing nan with mean\n",a)
print("sum of diagonals:",np.trace(a))
ar=np.where(a>5,1,0)
#ar=np.where(,a)
print("after discritization\n",ar)